<a href="https://colab.research.google.com/github/vaishnaviikommidi007/FreshBite/blob/main/customer_churn_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
print("all are imported successfully")

all are imported successfully

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving E Commerce Dataset.xlsx to E Commerce Dataset (2).xlsx

In [ ]:
import os
os.listdir()

['.config',
 'E Commerce Dataset.xlsx',
 'archive (1) (1).zip',
 'E Commerce Dataset (1).xlsx',
 'E Commerce Dataset (2).xlsx',
 'archive (1).zip',
 'sample_data']

In [ ]:
df = pd.read_excel("E Commerce Dataset.xlsx")

In [ ]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Data,Variable,Discerption
1,NaN,E Comm,CustomerID,Unique customer ID
2,NaN,E Comm,Churn,Churn Flag
3,NaN,E Comm,Tenure,Tenure of customer in organization
4,NaN,E Comm,PreferredLoginDevice,Preferred login device of customer

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  21 non-null     object
 2   Unnamed: 2  21 non-null     object
 3   Unnamed: 3  21 non-null     object
dtypes: float64(1), object(3)
memory usage: 804.0+ bytes

In [ ]:
import pandas as pd

excel_file = pd.ExcelFile("E Commerce Dataset.xlsx")

excel_file.sheet_names

['Data Dict', 'E Comm']

In [ ]:
df.describe()

NameError: name 'df' is not defined

In [ ]:
df = pd.read_excel("E Commerce Dataset.xlsx", sheet_name="E Comm")

FileNotFoundError: [Errno 2] No such file or directory: 'E Commerce Dataset.xlsx'

In [ ]:
import os

os.listdir()

['.config', 'sample_data']

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving E Commerce Dataset.xlsx to E Commerce Dataset.xlsx

In [ ]:
import os

os.listdir()

['.config', 'E Commerce Dataset.xlsx', 'sample_data']

In [ ]:
import pandas as pd

excel_file = pd.ExcelFile("E Commerce Dataset.xlsx")
print(excel_file.sheet_names)

['Data Dict', 'E Comm']

In [ ]:
import pandas as pd

df = pd.read_excel("E Commerce Dataset.xlsx", sheet_name="E Comm")

In [ ]:
df.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [ ]:
df.describe()

,CustomerID,Churn,Tenure,CityTier,WarehouseToHome,HourSpendOnApp,NumberOfDeviceRegistered,SatisfactionScore,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
count,5630.000000,5630.000000,5366.000000,5630.000000,5379.000000,5375.000000,5630.000000,5630.000000,5630.000000,5630.000000,5365.000000,5374.000000,5372.000000,5323.000000,5630.000000
mean,52815.500000,0.168384,10.189899,1.654707,15.639896,2.931535,3.688988,3.066785,4.214032,0.284902,15.707922,1.751023,3.008004,4.543491,177.223030
std,1625.385339,0.374240,8.557241,0.915389,8.531475,0.721926,1.023999,1.380194,2.583586,0.451408,3.675485,1.894621,2.939680,3.654433,49.207036
min,50001.000000,0.000000,0.000000,1.000000,5.000000,0.000000,1.000000,1.000000,1.000000,0.000000,11.000000,0.000000,1.000000,0.000000,0.000000
25%,51408.250000,0.000000,2.000000,1.000000,9.000000,2.000000,3.000000,2.000000,2.000000,0.000000,13.000000,1.000000,1.000000,2.000000,145.770000
50%,52815.500000,0.000000,9.000000,1.000000,14.000000,3.000000,4.000000,3.000000,3.000000,0.000000,15.000000,1.000000,2.000000,3.000000,163.280000
75%,54222.750000,0.000000,16.000000,3.000000,20.000000,3.000000,4.000000,4.000000,6.000000,1.000000,18.000000,2.000000,3.000000,7.000000,196.392500
max,55630.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,26.000000,16.000000,16.000000,46.000000,324.990000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5630 entries, 0 to 5629
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CustomerID                   5630 non-null   int64
 1   Churn                        5630 non-null   int64
 2   Tenure                       5366 non-null   float64
 3   PreferredLoginDevice         5630 non-null   object
 4   CityTier                     5630 non-null   int64
 5   WarehouseToHome              5379 non-null   float64
 6   PreferredPaymentMode         5630 non-null   object
 7   Gender                       5630 non-null   object
 8   HourSpendOnApp               5375 non-null   float64
 9   NumberOfDeviceRegistered     5630 non-null   int64
 10  PreferedOrderCat             5630 non-null   object
 11  SatisfactionScore            5630 non-null   int64
 12  MaritalStatus                5630 non-null   object
 13  NumberOfAddress              5630 non-null   int64
 14  Complain                     5630 non-null   int64
 15  OrderAmountHikeFromlastYear  5365 non-null   float64
 16  CouponUsed                   5374 non-null   float64
 17  OrderCount                   5372 non-null   float64
 18  DaySinceLastOrder            5323 non-null   float64
 19  CashbackAmount               5630 non-null   float64
dtypes: float64(8), int64(7), object(5)
memory usage: 879.8+ KB

In [ ]:
import os
print(os.getcwd)

<built-in function getcwd>

In [ ]:
import os
print(os.getcwd())

/content

In [ ]:
df.shape()

TypeError: 'tuple' object is not callable

In [ ]:
df.shape

(5630, 20)

In [ ]:
df.isnull().sum()

CustomerID                       0
Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64

In [ ]:
import pandas as pd
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
X_test.isnull().sum()

CustomerID                      0
Tenure                         51
PreferredLoginDevice            0
CityTier                        0
WarehouseToHome                45
PreferredPaymentMode            0
Gender                          0
HourSpendOnApp                 58
NumberOfDeviceRegistered        0
PreferedOrderCat                0
SatisfactionScore               0
MaritalStatus                   0
NumberOfAddress                 0
Complain                        0
OrderAmountHikeFromlastYear    57
CouponUsed                     48
OrderCount                     46
DaySinceLastOrder              60
CashbackAmount                  0
dtype: int64

In [ ]:
X_train.isnull().sum()

CustomerID                       0
Tenure                         213
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                206
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 197
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    208
CouponUsed                     208
OrderCount                     212
DaySinceLastOrder              247
CashbackAmount                   0
dtype: int64

In [ ]:
ten_med=X_train["Tenure"].median()

In [ ]:
X_train["Tenure"].fillna(ten_med, inplace=True)

/tmp/ipykernel_752/2849810238.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["Tenure"].fillna(ten_med, inplace=True)

In [ ]:
X_train["Tenure"] = X_train["Tenure"].fillna(ten_med)

In [ ]:
X_test["Tenure"] = X_test["Tenure"].fillna(ten_med)

In [ ]:
X_train["Tenure"].isnull().sum()

np.int64(0)

In [ ]:
X_train.isnull().sum()

CustomerID                       0
Tenure                           0
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                206
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 197
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    208
CouponUsed                     208
OrderCount                     212
DaySinceLastOrder              247
CashbackAmount                   0
dtype: int64

In [ ]:
ware_med=X_train["WarehouseToHome"].median()

In [ ]:
X_train["WarehouseToHome"]=X_train["WarehouseToHome"].fillna(ware_med)
X_test["WarehouseToHome"]=X_test["WarehouseToHome"].fillna(ware_med)

In [ ]:
X_train["WarehouseToHome"].isnull().sum()

np.int64(0)

In [ ]:
hour_spend=X_train["HourSpendOnApp"].mean()

In [ ]:
X_train["HourSpendOnApp"]=X_train["HourSpendOnApp"].fillna(hour_spend)
X_test["HourSpendOnApp"]=X_test["HourSpendOnApp"].fillna(hour_spend)

In [ ]:
coupon_med = X_train["CouponUsed"].median()

X_train["CouponUsed"] = X_train["CouponUsed"].fillna(coupon_med)

X_test["CouponUsed"] = X_test["CouponUsed"].fillna(coupon_med)

In [ ]:
X_train.isnull().sum()

CustomerID                       0
Tenure                           0
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                  0
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                   0
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    208
CouponUsed                       0
OrderCount                     212
DaySinceLastOrder              247
CashbackAmount                   0
dtype: int64

In [ ]:
Order_med = X_train["OrderCount"].median()

X_train["OrderCount"] = X_train["OrderCount"].fillna(Order_med)

X_test["OrderCount"] = X_test["OrderCount"].fillna(Order_med)

In [ ]:
day_med = X_train["DaySinceLastOrder"].median()

X_train["DaySinceLastOrder"] = X_train["DaySinceLastOrder"].fillna(day_med)

X_test["DaySinceLastOrder"] = X_test["DaySinceLastOrder"].fillna(day_med)

In [ ]:
X_train.isnull().sum()

NameError: name 'X_train' is not defined